config/routes.rb
Stream::Application.routes.draw do
  root :to => 'articles#index'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/sign_out' => 'sessions#destroy', :as => 'sign_out'

  match '/about' => 'about#index'

  resources :articles, :except => :show
  resources :users, :except => [:new, :create]
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "UTF-8"}
    %title Stream
    /= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    /= stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
    /  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"

    = yield :javascript

    = csrf_meta_tag
  %body
    #container
      %header#header
        %h1= link_to "Stream", root_path

        = link_to "RSS", articles_path(:format => :rss), :id => "rss"
        %nav
          %ul
            %li= link_to "About", about_path
            %li= link_to "Mendicant University", "http://university.rubymendicant.com", :target => "_blank"
            - if signed_in?
              %li= link_to "Post article", new_article_path
              %li= link_to "Sign out", sign_out_path
            - else
              %li= link_to "Sign in with Github", sign_in_path

      = render_flash_messages

      %section#content
        = yield

      %footer#footer
        %p A Mendicant University Project